development:
    ssg:
        email_address:                      "no-reply@sredisvojgrad.com"
    fb:
        site_url:                           https://graph.facebook.com
        scope:                              "email,user_photos"