development:
  ssg:
    email_address:          "no-reply@sredisvojgrad.com"
    auth_enabled:           False
    auth_username:          "username"
    auth_password:          "pass"
    host:                   "localhost"
    port:                   "3000"
  fb:
    site_url:               "https://graph.facebook.com"
    scope:                  "email,user_photos"
    application_id:         # REQUIRED
    secret_key:             # REQUIRED
  aws:
    access_key:             # REQUIRED  
    access_secret:          # REQUIRED
  misc:
    unique_view_epsilon:    3600