development:
    ssg:
        email_address:                      "no-reply@sredisvojgrad.com"
        auth_enabled:						true
        auth_username:						"username"
        auth_password:						"pass"
    fb:
        site_url:                           https://graph.facebook.com
        scope:                              "email,user_photos"
 