development:
  ssg:
    email_address:          "no-reply@sredisvojgrad.com"
    auth_enabled:           False
    auth_username:          "username"
    auth_password:          "pass"
    host:                   "localhost"
    port:                   "3000"
  fb:
    site_url:               "https://graph.facebook.com"
    scope:                  "email,user_photos"
    application_id:         463608053690571
    secret_key:             dbe6240714c1699358c828ddb741dfab
  aws:
    access_key:             AKIAIDBQTR4BEK6W5XTQ
    access_secret:          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        
  misc:
    unique_view_epsilon:    3600